[smtp]
host = "smtp.gmail.com"
port = 587
user = "ary.sham026@gmail.com"
password = "fwva yinw rshw jlwi"   # use an App Password if using Gmail
use_tls = true
INIT_TOKEN = "09JpxouqhACq8mOM2wRfBESBerx4kz"
